### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by pixlperfect01** [LucGamesYT/ScoreboardAPI#4]
You seem to have discord messages turned off for those who aren’t friends or are not in a shared server.
Due to this, this was the only way I could think of to contact you(I am PixlPerfect01).

This is the message/question I wanted to send:

You don’t need to accept the friend request, it’s just the only way I could message you(clicking on your name).

I’m fairly new to Minecraft server management and plugins, and haven’t done that much java in a few years, and I was wondering if you could write a quick example program for the ScoreboardAPI and tell me where to put it. 

Thanks in advance!
Lmk if you can, if not some tips/tricks on how to use the api would be appreciated!

**Comment by Kaooot** [comment]
Hey @pixlperfect01 
Some instructions can be found in the README file of this project.

Greetings
Kaooot

**Comment by LucGamesYT** [comment]
As Kaot already said, I have an example of how to use the plugin/API described in the README

**Comment by pixlperfect01** [comment]
Y’know, it woulda helped to read the readme, sorry for bothering lol
