### ISSUE TITLE
Gradle: 409 Code when compiling V1.4

### ISSUE THREAD

**Issue by squeeglii** [LucGamesYT/ScoreboardAPI#5]
![image](https://user-images.githubusercontent.com/16578982/97804561-a36d3b80-1c48-11eb-86fa-1098b3cd26ab.png)

**Comment by LucGamesYT** [comment]
This is a Maven project, not a Gradle

**Comment by Kaooot** [comment]
As @LucGamesYT already said, you have to work with the Maven Build Tool if you'd like to use his ScoreboardAPI.

I think this issue can be closed now.
